services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: andrey
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: andrey
      DB_PASS: password123
      DB_NAME: postgres

      
volumes:
      pgdata:
  
